name: Deploy to Github Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # .NET Core環境の構築
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
      # Blazor WebAssemblyが使えるSDKを指定
        dotnet-version: 3.1.x
    - name: Build Application
      # デプロイするProjectを指定 (今回は"BlazorApp")
      run: dotnet publish -c Release ./BlazorApp/BlazorApp.csproj

    - name: Deploy
      uses: peaceiris/actions-display@v3
      with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           # publishコマンドで出力されたファイルをdisplayブランチにpush
           publish_dir: ./BlazorApp/bin/Release/netstandard2.1/publish/wwwroot/
